# Generated by Django 4.2 on 2023-04-09 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['Tamamlandi']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='Aciklama',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='Baslik',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='Kullanici',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='Olusturuldu',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='complete',
            new_name='Tamamlandi',
        ),
    ]
