# Generated by Django 4.2 on 2023-04-09 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_task_options_rename_description_task_aciklama_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Tamamlandi',
            new_name='complete',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Olusturuldu',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Aciklama',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Baslik',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Kullanici',
            new_name='user',
        ),
    ]
